import Head from "next/head";
// import localFont from "next/font/local";
import styles from "../styles/Home.module.css";
import Script from 'next/script'
import ComponentA from "next2/ComponentA"
import dynamic from "next/dynamic";
// import PaymentForm from "pagos/PaymentForm"

// const PaymentForm = dynamic(() => import('pagos/PaymentForm'), { ssr: false });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script type="module" src="http://localhost:4173/assets/remoteEntry.js?t=1725933395589"/>
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <h2>Microfrontend Next.js App v14</h2>
          <ComponentA />
          {/* <PaymentForm/> */}
          <p>Hola mundo</p>
        </main>
      </div>
    </>
  );
}

